language: python
sudo: required
python:
    - "3.5"

env:
  matrix:
    - CGAL_VER=4.9

addons:
  apt:
    packages:
    - libmpfr-dev
    - libboost-atomic-dev
    - libboost-chrono-dev
    - libboost-date-time-dev
    - libboost-system-dev
    - libboost-thread-dev
    - libeigen3-dev
    - swig
    - python-dev
    - python-numpy
    - python3-dev
    - python3-numpy
    - openjdk-7-jdk

install:
  - git clone https://github.com/CGAL/cgal.git
  - cd cgal
  - git checkout releases/CGAL-${CGAL_VER}
  - cmake -DCMAKE_INSTALL_PREFIX=/usr .
  - make -j2
  - sudo make install
  - cd ..

script:
  - python -m sysconfig
  - cmake -DBUILD_JAVA=OFF
    -DPYTHON_INCLUDE_DIR=/home/travis/virtualenv/python3.5.3/include/python3.5m
    -DPYTHON_LIBRARY=/opt/python/3.5.3/lib/libpython3.5m.so
    -DPYTHON_EXECUTABLE=/home/travis/virtualenv/python3.5.3/bin/python
    -DPYTHON_MODULE_PATH=/home/travis/virtualenv/python3.5.3/site-packages
    .
  - make install -j2 && ctest -j2 --output-on-failure
